# 1. Alegem imaginea de Docker cu care lucrăm
image: node:20

# 2. Definim ordinea etapelor
stages:
  - build
  - deploy

# 3. Integrarea Continuă (CI) - Construirea aplicației
build_app:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/ # Salvează rezultatul. Pune 'build/' dacă folosești Create React App
    expire_in: 1 hour

# 4. Livrarea Continuă (CD) - Publicarea pe GitLab Pages
pages:
  stage: deploy
  script:
    # GitLab Pages cere obligatoriu ca fișierele finale să fie într-un folder numit 'public'
    - mv dist/ public/
  artifacts:
    paths:
      - public
  only:
    - master # Se execută doar când codul ajunge pe branch-ul principal
